/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpecialitiesRouteImport } from './routes/specialities'
import { Route as SessionsRouteImport } from './routes/sessions'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JoinRouteImport } from './routes/join'
import { Route as HoroscopesRouteImport } from './routes/horoscopes'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CountriesRouteImport } from './routes/countries'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AstrologersIndexRouteImport } from './routes/astrologers.index'
import { Route as SpecialitiesSlugRouteImport } from './routes/specialities.$slug'
import { Route as SessionsSlugRouteImport } from './routes/sessions.$slug'
import { Route as HoroscopesSignRouteImport } from './routes/horoscopes.$sign'
import { Route as CountriesSlugRouteImport } from './routes/countries.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AstrologersSlugRouteImport } from './routes/astrologers.$slug'
import { Route as ApiEnhancePostRouteImport } from './routes/api.enhance-post'

const SpecialitiesRoute = SpecialitiesRouteImport.update({
  id: '/specialities',
  path: '/specialities',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionsRoute = SessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const HoroscopesRoute = HoroscopesRouteImport.update({
  id: '/horoscopes',
  path: '/horoscopes',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CountriesRoute = CountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AstrologersIndexRoute = AstrologersIndexRouteImport.update({
  id: '/astrologers/',
  path: '/astrologers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecialitiesSlugRoute = SpecialitiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SpecialitiesRoute,
} as any)
const SessionsSlugRoute = SessionsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => SessionsRoute,
} as any)
const HoroscopesSignRoute = HoroscopesSignRouteImport.update({
  id: '/$sign',
  path: '/$sign',
  getParentRoute: () => HoroscopesRoute,
} as any)
const CountriesSlugRoute = CountriesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CountriesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AstrologersSlugRoute = AstrologersSlugRouteImport.update({
  id: '/astrologers/$slug',
  path: '/astrologers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEnhancePostRoute = ApiEnhancePostRouteImport.update({
  id: '/api/enhance-post',
  path: '/api/enhance-post',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/faq': typeof FaqRoute
  '/horoscopes': typeof HoroscopesRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/specialities': typeof SpecialitiesRouteWithChildren
  '/api/enhance-post': typeof ApiEnhancePostRoute
  '/astrologers/$slug': typeof AstrologersSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/horoscopes/$sign': typeof HoroscopesSignRoute
  '/sessions/$slug': typeof SessionsSlugRoute
  '/specialities/$slug': typeof SpecialitiesSlugRoute
  '/astrologers/': typeof AstrologersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/faq': typeof FaqRoute
  '/horoscopes': typeof HoroscopesRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/specialities': typeof SpecialitiesRouteWithChildren
  '/api/enhance-post': typeof ApiEnhancePostRoute
  '/astrologers/$slug': typeof AstrologersSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/horoscopes/$sign': typeof HoroscopesSignRoute
  '/sessions/$slug': typeof SessionsSlugRoute
  '/specialities/$slug': typeof SpecialitiesSlugRoute
  '/astrologers': typeof AstrologersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/countries': typeof CountriesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/editor': typeof EditorRoute
  '/faq': typeof FaqRoute
  '/horoscopes': typeof HoroscopesRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/sessions': typeof SessionsRouteWithChildren
  '/specialities': typeof SpecialitiesRouteWithChildren
  '/api/enhance-post': typeof ApiEnhancePostRoute
  '/astrologers/$slug': typeof AstrologersSlugRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/countries/$slug': typeof CountriesSlugRoute
  '/horoscopes/$sign': typeof HoroscopesSignRoute
  '/sessions/$slug': typeof SessionsSlugRoute
  '/specialities/$slug': typeof SpecialitiesSlugRoute
  '/astrologers/': typeof AstrologersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/countries'
    | '/dashboard'
    | '/editor'
    | '/faq'
    | '/horoscopes'
    | '/join'
    | '/login'
    | '/sessions'
    | '/specialities'
    | '/api/enhance-post'
    | '/astrologers/$slug'
    | '/blog/$slug'
    | '/countries/$slug'
    | '/horoscopes/$sign'
    | '/sessions/$slug'
    | '/specialities/$slug'
    | '/astrologers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/countries'
    | '/dashboard'
    | '/editor'
    | '/faq'
    | '/horoscopes'
    | '/join'
    | '/login'
    | '/sessions'
    | '/specialities'
    | '/api/enhance-post'
    | '/astrologers/$slug'
    | '/blog/$slug'
    | '/countries/$slug'
    | '/horoscopes/$sign'
    | '/sessions/$slug'
    | '/specialities/$slug'
    | '/astrologers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/countries'
    | '/dashboard'
    | '/editor'
    | '/faq'
    | '/horoscopes'
    | '/join'
    | '/login'
    | '/sessions'
    | '/specialities'
    | '/api/enhance-post'
    | '/astrologers/$slug'
    | '/blog/$slug'
    | '/countries/$slug'
    | '/horoscopes/$sign'
    | '/sessions/$slug'
    | '/specialities/$slug'
    | '/astrologers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  CountriesRoute: typeof CountriesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  EditorRoute: typeof EditorRoute
  FaqRoute: typeof FaqRoute
  HoroscopesRoute: typeof HoroscopesRouteWithChildren
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  SessionsRoute: typeof SessionsRouteWithChildren
  SpecialitiesRoute: typeof SpecialitiesRouteWithChildren
  ApiEnhancePostRoute: typeof ApiEnhancePostRoute
  AstrologersSlugRoute: typeof AstrologersSlugRoute
  AstrologersIndexRoute: typeof AstrologersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/specialities': {
      id: '/specialities'
      path: '/specialities'
      fullPath: '/specialities'
      preLoaderRoute: typeof SpecialitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sessions': {
      id: '/sessions'
      path: '/sessions'
      fullPath: '/sessions'
      preLoaderRoute: typeof SessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horoscopes': {
      id: '/horoscopes'
      path: '/horoscopes'
      fullPath: '/horoscopes'
      preLoaderRoute: typeof HoroscopesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countries': {
      id: '/countries'
      path: '/countries'
      fullPath: '/countries'
      preLoaderRoute: typeof CountriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/astrologers/': {
      id: '/astrologers/'
      path: '/astrologers'
      fullPath: '/astrologers/'
      preLoaderRoute: typeof AstrologersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialities/$slug': {
      id: '/specialities/$slug'
      path: '/$slug'
      fullPath: '/specialities/$slug'
      preLoaderRoute: typeof SpecialitiesSlugRouteImport
      parentRoute: typeof SpecialitiesRoute
    }
    '/sessions/$slug': {
      id: '/sessions/$slug'
      path: '/$slug'
      fullPath: '/sessions/$slug'
      preLoaderRoute: typeof SessionsSlugRouteImport
      parentRoute: typeof SessionsRoute
    }
    '/horoscopes/$sign': {
      id: '/horoscopes/$sign'
      path: '/$sign'
      fullPath: '/horoscopes/$sign'
      preLoaderRoute: typeof HoroscopesSignRouteImport
      parentRoute: typeof HoroscopesRoute
    }
    '/countries/$slug': {
      id: '/countries/$slug'
      path: '/$slug'
      fullPath: '/countries/$slug'
      preLoaderRoute: typeof CountriesSlugRouteImport
      parentRoute: typeof CountriesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/astrologers/$slug': {
      id: '/astrologers/$slug'
      path: '/astrologers/$slug'
      fullPath: '/astrologers/$slug'
      preLoaderRoute: typeof AstrologersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/enhance-post': {
      id: '/api/enhance-post'
      path: '/api/enhance-post'
      fullPath: '/api/enhance-post'
      preLoaderRoute: typeof ApiEnhancePostRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface CountriesRouteChildren {
  CountriesSlugRoute: typeof CountriesSlugRoute
}

const CountriesRouteChildren: CountriesRouteChildren = {
  CountriesSlugRoute: CountriesSlugRoute,
}

const CountriesRouteWithChildren = CountriesRoute._addFileChildren(
  CountriesRouteChildren,
)

interface HoroscopesRouteChildren {
  HoroscopesSignRoute: typeof HoroscopesSignRoute
}

const HoroscopesRouteChildren: HoroscopesRouteChildren = {
  HoroscopesSignRoute: HoroscopesSignRoute,
}

const HoroscopesRouteWithChildren = HoroscopesRoute._addFileChildren(
  HoroscopesRouteChildren,
)

interface SessionsRouteChildren {
  SessionsSlugRoute: typeof SessionsSlugRoute
}

const SessionsRouteChildren: SessionsRouteChildren = {
  SessionsSlugRoute: SessionsSlugRoute,
}

const SessionsRouteWithChildren = SessionsRoute._addFileChildren(
  SessionsRouteChildren,
)

interface SpecialitiesRouteChildren {
  SpecialitiesSlugRoute: typeof SpecialitiesSlugRoute
}

const SpecialitiesRouteChildren: SpecialitiesRouteChildren = {
  SpecialitiesSlugRoute: SpecialitiesSlugRoute,
}

const SpecialitiesRouteWithChildren = SpecialitiesRoute._addFileChildren(
  SpecialitiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  CountriesRoute: CountriesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  EditorRoute: EditorRoute,
  FaqRoute: FaqRoute,
  HoroscopesRoute: HoroscopesRouteWithChildren,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  SessionsRoute: SessionsRouteWithChildren,
  SpecialitiesRoute: SpecialitiesRouteWithChildren,
  ApiEnhancePostRoute: ApiEnhancePostRoute,
  AstrologersSlugRoute: AstrologersSlugRoute,
  AstrologersIndexRoute: AstrologersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
